import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'dipak',
      email: 'deepraj41352@gmail.com',
      password: bcrypt.hashSync('123123'),
      isAdmin: true,
    },
    {
      name: 'karan',
      email: 'karan41352@gmail.com',
      password: bcrypt.hashSync('123123'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirf',
      category: 'Shirts',
      image: '/image/shirt.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: '5',
      numReviews: '11',
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Nike T-shirt',
      slug: 'nike-t-shirf',
      category: 'T-Shirts',
      image: '/image/T-shart.jpg',
      price: 520,
      countInStock: 10,
      brand: 'Nike',
      rating: '4.5',
      numReviews: '14',
      description: 'high quality T- shirt',
    },
    {
      // _id: '3',
      name: 'Net Pant',
      slug: 'net-fit-pant',
      category: 'Pant',
      image: '/image/pant1.jpg',
      price: 500,
      numReviews: '15',
      countInStock: 10,
      brand: 'Net',
      rating: '3.5',
      description: 'high quality Pant',
    },
    {
      // _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pant',
      image: '/image/pant2.jpg',
      price: 1180,
      countInStock: 10,
      brand: 'Adidas',
      rating: '5',
      numReviews: 9,
      description: 'high quality Pant',
    },
  ],
};
export default data;
