const data = {
  products: [
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirf',
      category: 'Shirts',
      image: '/image/shirt.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      numReviews: '10',
      description: 'high quality shirt',
    },
    {
      name: 'Nike T-shirt',
      slug: 'nike-t-shirf',
      category: 'T-Shirts',
      image: '/image/T-shart.jpg',
      price: 520,
      countInStock: 20,
      brand: 'Nike',
      numReviews: '10',
      description: 'high quality T- shirt',
    },
    {
      name: 'Net Pant',
      slug: 'net-fit-pant',
      category: 'Pant',
      image: '/image/pant1.jpg',
      price: 500,
      countInStock: 30,
      brand: 'Net',
      numReviews: '10',
      description: 'high quality Pant',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pant',
      image: '/image/pant2.jpg',
      price: 1180,
      countInStock: 30,
      brand: 'Adidas',
      numReviews: '10',
      description: 'high quality Pant',
    },
  ],
};
export default data;
